### PR TITLE
Misc fixs

### PR DESCRIPTION
**Pull request by jackolantern**
The main fix is in 3931ca6 `KafkaSource.java`  The problem is that the ConsumerIterator.hasNext() method will block forever if there is no timeout set (`consumer.timeout.ms`), or until a new message is written to kafka.  This means that unless the batchsize is actually reached, no messages will be written to the channel.
If `consumer.timeout.ms` is supplied, the way exceptions were being handled, the messages would _still_ not be written to the channel.

The rest of the fixes involved things like code formatting, dead code regions, etc.  The only other large change was making `extra-dependencies` a local-repo and adding it to the pom file.  This will make it easier for people to build this project.

### CODE REVIEW

**Comment by jackolantern** [comment]
@baniuyao if you want to see an example of the problem 3931ca6 fixes, create a kafka topic with 1 message in it, and set your kafka source batchsize to 2, and do not set consumer.timeout.ms.  When you start flume, you will see that the message is never written to the channel.  Then write another message to the topic, and you will see both messages in the channel.

**Comment by yrjsg** [comment]
Since I'm not very familiar with mvn, some people told me that kafka-0.7.2.jar is not on the maven repro before, so I put this jar in the extra-dependencies directory. I think put this dependency in pom is a good idea.

Plus, the bug fix seems really cool, but I need some time for test:). You know, weekend is a festival in family:)

**Comment by yrjsg** [comment]
I've read the code and there's a question:
If a timeoust block occurs and, by your code, it will be BACKOFF status. What is the flume behavior after that? Will flume get these messages again and be BACKOFF status again. If it happened, a dead loop is there. Am I right?

**Comment by jackolantern** [comment]
I believe the behavior is like this:

**If no timeout occurs**: the events will be written to the channel, and the status will be READY, which is what we want, because if no timeout occurred it means that there was at least `batchsize` data in kafka, and we should continue to query at the current frequency.

**If a timeout occurs**: the events will be written to the channel, and the status will be BACKOFF, which is what we want, because if timeouts are occurring, it means that we should reduce the frequency by which we query the source.  After the timeout, there are three cases:
- A kafka producer writes data to the kafka broker at a rate equal to, or greater than `batchsize` per flume query.      In which case the next query will result in `batchsize` worth of data being written to the channel, and a status of READY.  (I believe this READY status will make flume resume its configured query frequency, and undo all of the delays added due to consecutive BACKOFF statuses, but maybe it just undoes one BACKOFF status?  I am not 100% sure, but either way, it works)
- A kafka producer writes data to the kafka broker at a rate less than `batchsize` per flume query.  In this case another timeout exception occurrs, and a set of messages less than `batchsize` is written to the channel, and results in a BACKOFF status, which will cause flume to query this source less often (which is what we want, since the amount of data we are writing is not enough to fill a batch.)
- The broker is never written to again.  In this case, timeouts continue to be raised, and no messages are written to the channel, and consecutive BACKOFF statuses are returned, which will cause `maxBackoff` to be quickly reached, and so flume will query this source at the lowest possible frequency, which is the best we can reasonably ask for.

A more serious issue is on line #70 (https://github.com/jackolantern/flume-kafka/blob/835824a781c3b57620972473493b41f8b1fd25c8/src/main/java/com/vipshop/flume/source/kafka/KafkaSource.java#L70) In this case an exception was thrown while writing the messages to the channel.  In this case, those messages are lost (but this is what the current behavior is as well.)  Because we are using the kafka high level api, the offsets are probably already committed to zookeeper by this time, so there is really not much we can do (that I can see).  Either this was a one time issue, and so at most `batchsize` messages were lost, or this is a recurring issue, and no further messages are written to the channel.  
In my environment, these issues are caught, and there are process in place to correct the data, but it is definitely a problem with the library, but unfortunately I am not sure of the best way to address it.

**Comment by yrjsg** [comment]
## consumer.timeout.ms

I found actually Kafka do not have `batchSize` concept. What looks like `batchSize` is `fetchSize` in Kafka configuration. Description of `fetchSize` is:

> controls the number of bytes of messages to attempt to fetch in one request to the Kafka server

I am thinking remove `batchSize` feature in next version, and for replacement, use kafka original `fetchSize`.

In this circumstances, is the fix on `batchSize` still take effect?

## kafka-0.7.2.jar dependency

The kafka-0.7.2.jar dependency is really an touch problem. Recently, I'm working on add this project to Apache Flume and flume teammates found that kafka-0.7.2.jar is not in maven repo, we are looking for solution for that. I want to show flume guys your solution.

Really thanks from Shanghai :)

**Comment by jackolantern** [comment]
I think that you are asking me whether this fix will still work if you remove `batchSize` and replace it with `fetchSize`.  It would depend on what specific changes you would make, but I believe that you will still have to do something similar to what I have done here in order to correctly handle timeouts and to make sure that events are written to the channel as they are received from kafka, not just when `fetchSize` is actually reached.

**Comment by yrjsg** [comment]
Yep, `batchSize` is not the same action as `fetchSize`. For `batchSize`, flume will request kafka serveral times to fullfill the event list so that the `timeout` is really important. As I dig into kafka documents, the `fetchSize` would act like this, flume request kafka for only one time for a set of message which is of `fetchSize` size. 

For my opinion, I'd like to give responsibilities of setting parameters to users. I am not sure if I need to put some default parameters value.

**Pull request closed without merging**
